### PR TITLE
Update tutorial-0.rst

### PR DESCRIPTION
**Pull request by nashella**
fix typo in command line

### CODE REVIEW

**Comment by cflee** [comment]
Note: This would break the instructions for Linux/OS X users, as they need to use the colon to separate items in the classpath, instead of the semicolon.

**Comment by nashella** [comment]
oh ok I So it's different on Windows... I will make a better change, thanks

**Comment by freakboy3742** [comment]
Apologies for the delay in merging this patch - I didn't notice that you had updated it after the initial review. Thanks for the contribution!

**Comment by nashella** [comment]
Hey no worry :) I should have made à comment.
And today is my birthday so it's perfect timing! Thank you :)

**Pull request merged**
