### PR TITLE
Included isalpha()

### PR DESCRIPTION
**Pull request by shyamsunder007**

### CODE REVIEW

**Comment by eliasdorneles** [comment]
Hi @shyamsunder007 -- the build is failing because of some style checks, can you have a look?
You might find helpful to [run the style checks locally before commiting](http://voc.readthedocs.io/en/latest/internals/contributing.html#running-the-code-style-checks).

**Comment by eliasdorneles** [comment]
Still some style checks failing, now on the Java code: https://travis-ci.org/pybee/voc/jobs/211023537#L185-L190
It's good to [run the style checks locally](http://voc.readthedocs.io/en/latest/internals/contributing.html#running-the-code-style-checks).

**Comment by eliasdorneles** [comment]
Ooops, just realized this implements the same as https://github.com/pybee/voc/pull/413 which I've just merged!

I like this version better (docstring, simpler code), would consider submitting a new PR that refactors the current version to this one?
I'd merge it, as long as it passes the same tests on #413 :+1:

**Comment by shyamsunder007** [comment]
then i am closing this pr

**Pull request closed without merging**
