### PR TITLE
Plumb the slice() constructor to the Slice object.

### PR DESCRIPTION
**Pull request by skimbrel**
This should unblock running a whole fleet of binop tests!

### CODE REVIEW

**Comment by glasnt** [comment]
Looks good! Travis is just complaining about 700+ unexpected successes. Clean those up and this is good to go 🎉

**Comment by skimbrel** [comment]
All right, that last commit should get the few I missed with my script.

**Comment by glasnt** [comment]
This needs to be rebased before it can be merged.. and Travis has decided to ignore d2aeadb, so that's nice

**Comment by skimbrel** [comment]
Rebased. Let's give that a shot against Travis.

**Comment by freakboy3742** [comment]
Awesome! Thanks Sam.

And now, something that I don't get to say very often: Come down to Australia and collect your coin! :-)

**Pull request merged**
