### PR TITLE
Refs #361 Fix

### PR DESCRIPTION
**Pull request by ASP1234**
**Changes**

- Change exception from Runtime to ClassNotFound in importPythonModule. This is because the method itself throws ClassNotFound exception rather than Runtime

- Removed the try catch block, This is because if a module doesn't exist in python too then why are we catching the ClassNotFoundException rather than simply throwing it. Main reason of issue#361

**Testing**

- test_import successfully completed

- Expected o/p for issue #361

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Changes without tests are *very* suspicious - and it's not clear why these changes fix the problem you've described.

**Comment by ASP1234** [comment]
- Import tests are passing with these changes

- It produces the expected #361 behavior

- We need to throw ClassNotFound Exception rather than throwing runtime exception here

**Comment by goanpeca** [comment]
@ASP1234 could you perform a rebase with the latest master?

Cheers

**Comment by phildini** [comment]
Hi there! It looks like this PR might be dead, so we're closing it for now. Feel free to re-open it if you'd like to continue, or think about directing your efforts to https://github.com/beeware/briefcase or https://github.com/beeware/toga. Both of these have more active development right now. 😄

**Pull request closed without merging**
