### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by cherub96**

### CODE REVIEW

**Comment by cherub96** [comment]
Hey, I'm getting skipped=2 test cases in my last commit. What should I do to remove it?

**Comment by cflee** [comment]
@cherub96 It's actually expected, so no problem with that - the test suite is passing with the green checkmark now that no test cases are resulting in `FAIL` or `unexpected success`.

If you want to see which test cases are being skipped, you can look at the Travis CI build log and search for `skipped`. The specific test case is marked with `@skip`; you can remove that and then run the test to see what is the expected output.

**Comment by cherub96** [comment]
@cflee , my last commit shows a red cross, there are no FAIL or unexpected success test cases but it have 2 skipped cases.
This is what it shows in Travis CI
test_unpack_sequence_overflow (tests.structures.test_sequences.SequenceTests) ... skipped 'Feature not yet implemented'
test_unpack_sequence_underflow (tests.structures.test_sequences.SequenceTests) ... skipped 'Feature not yet implemented'

**Comment by cflee** [comment]
@cherub96 I'm not sure which commit that is. Could you put a link to the Travis CI build that has a red cross?

For this PR, it looks like your last commit is 8de19de, and the [Travis CI build log says it passed](https://travis-ci.org/pybee/voc/builds/121532959).

**Comment by cherub96** [comment]
@cflee , The commit [[6f09383|https://github.com/pybee/voc/pull/118/commits/6f09383e0132d9c79dbea322e73d447425614da6 ]], shows a red cross.

**Comment by cherub96** [comment]
The commit [6f09383](https://github.com/pybee/voc/pull/118/commits/6f09383e0132d9c79dbea322e73d447425614da6)

**Comment by cherub96** [comment]
Okay, got it :). Thanks @cflee.

**Pull request merged**
