### PR TITLE
Implementation of test-power-complex for Float.java

### PR DESCRIPTION
**Pull request by Deepayan-Ghosh**
Implementation of a floating number raised to a complex power, corresponding to the test ```test_power_complex``` in ```test_float.py``` for type ```Float.java```.

### CODE REVIEW

**Comment by Deepayan-Ghosh** [comment]
I do not how the build failed, I ran the test again on my laptop using ```python setup.py test -s tests.datatypes.test_float``` it is not showing any errors. Am I doing something wrong with the testing?

**Comment by eliasdorneles** [comment]
Hm, looks like it's failing for this case:

```
E     >>> x = 2.3456
E     >>> y = 3.14159265j
E     >>> x **= y
E     >>> x
E   - (-0.8946025309573877+0.44686274358536093j)
E   ?                                      ^^^
E   + (-0.8946025309573877+0.446862743585361j)
E   ?  
```

Maybe it's a matter of precision?
This will need some more digging...

**Comment by cflee** [comment]
If it's purely a rounding issue, can add to the `substitutions`, like:

https://github.com/pybee/voc/blob/da6dca3efe5501427c358a87a9166ce886050f94/tests/datatypes/test_complex.py#L50-L60

**Comment by Deepayan-Ghosh** [comment]
@cflee On adding the following lines to ```test_float.py```:
```
class BinaryFloatOperationTests(BinaryOperationTestCase, TranspileTestCase):
    data_type = 'float'

    substitutions = {
        "(-0.8946025309573877+0.446862743585361j)": [
            "(-0.8946025309573877+0.44686274358536093j)"
        ]
    }
    ...........................
```
the test ```test_float.BinaryFloatOperationTests.test_modulo_int``` seems to fail. The error seems to lie here:
```
  >>> x = -3.14159
  >>> y = -5
  >>> x % y
- -3.1415900000000008
+ -3.14159
```
Should I add the substitution to ```test_complex.py``` rather than ```test_float.py``` but we are testing float operation, right?

**Comment by cflee** [comment]
Look inside the `tests/utils.py` file, there are existing substitutions including that one for pi. Those lines are _replacing_ the entire substitutions dict, but you can just copy/add to the substitutions instead. There is at least one other place in the test suite which does that, if you get your text editor to search for it.

**Comment by Deepayan-Ghosh** [comment]
@cflee Done. Checks passed.

**Comment by Deepayan-Ghosh** [comment]
@eliasdorneles Can you please review this PR? Thanks. :smile:

**Pull request merged**
