### PR TITLE
Modifications to get the CI system back into working order

### PR DESCRIPTION
**Pull request by freakboy3742**
This modifies the compiler to speed up some hotspots, cleans up some tests failures found as a result, and fixes an infinite loop that was causing a pathologically slow test.

Includes some work from @skimbrel in a hope to get the whole thing working faster.

### CODE REVIEW

**Comment by DylanGraham** [comment]
Nice, it went from around 30 minutes to just under 19 minutes on my i5-3570 CPU @ 3.40GHz

**Comment by DylanGraham** [comment]
Running on a dual socket Haswell server with `py.test -n24` this completed in 3.58 minutes.

**Comment by freakboy3742** [comment]
😮 Wow... How many effective cores is that? Just trying to work out if using the parallel approach in our CI server might be an option...

**Comment by DylanGraham** [comment]
This is with hyper threading disabled, so using all 24 real cores of two E5-2690 v3 @ 2.60GHz
```
command         time (m)
py.test -n10	6.34
py.test -n12	6.22
py.test -n14	5.73
py.test -n14	5.71
py.test -n16	5.13
py.test -n18	4.59
py.test -n20	4.10
py.test -n22	3.79
py.test -n24	3.58
```

**Comment by freakboy3742** [comment]
Hrm. /me wonders how many cores a Travis CI worker has...

**Pull request merged**
