### PR TITLE
add error message for too large code

### PR DESCRIPTION
**Pull request by leasunhy**
refs #406

### CODE REVIEW

**Comment by cflee** [comment]
I think we need tests to make sure that this is working as expected.

Also, some quick thoughts:
- Since this relies on the start position of the instruction, and instructions are variable length, it might let a slightly-too-long method through.
- The limit should be <= 65534 bytes, as stated in the [JVM 7 spec](http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.3):
  > limiting the maximum size of the generated Java Virtual Machine code for any method, instance initialization method, or static initializer (the size of any code array) to 65534 bytes.
- Also from the above, it needs to check the length of resulting method, instance initialization method, and static initializers. I haven't dug into the code to check this, but definitely these need to be tested to demonstrate that the check correctly.
- Would it be more accurate and clearer to check the Code object's `code_length` property elsewhere, maybe even in the constructor if possible? It might be less surprising to see this error being raised from Code than from LineNumberTable, since it's actually the total size of the Code object's opcodes that is the problem, not LineNumberTable size.
- The message could be more informative and briefly refer to the ~64KiB/65534 bytes method size limit.

**Comment by leasunhy** [comment]
@cflee Thank you for reviewing!
Frankly speaking, I've thought of adding a test for this... But I wondered where I should add the test to (because it seems that all other tests are the `compare-output-with-CPython` type of tests)... I didn't know whether it's appropriate for me to add a `code_length_test.py` only for this purpose... So I just tested by hand.. :-(

All of your points are valid! Please allow me some time to figure out how to improve this PR :-)

Thank you for your advice :-)

**Comment by freakboy3742** [comment]
I'll also echo @cflee's comments - and add that the best place I can think of to deal with the offset problem is in `voc/python/blocks.py`, in `transpile_code()` - that's where the code offsets are evaluated.

**Comment by leasunhy** [comment]
Ready for review here :-)

**Pull request merged**
