### PR TITLE
some Set functions

### PR DESCRIPTION
**Pull request by Saurabh--Kumar**
This PR has implementation for isdisjoint(), issuperset(), issubset(), symmetric_difference() and symmetric_difference_update() methods for set. Added exception handling to union() and intersection() methods.

### CODE REVIEW

**Comment by freakboy3742** [comment]
This has some overlap with functionality that was recently added; can you resolve the conflicts and push an update?

**Comment by Saurabh--Kumar** [comment]
@freakboy3742 Removed merge conflicts.

**Comment by deep110** [comment]
@Saurabh--Kumar Hi, I think in your implementation of issubset() or issuperset() you are not taking care of iterables and frozensets which was passing with last merge.

**Comment by Saurabh--Kumar** [comment]
Yes @deep110. You are right. I had forgotten that part while writing code. My implementation was not taking care of those cases, I have removed my implementation of those methods. Infact, you helped me to modify isdisjoint() method to include those cases. Thanks. :)

**Comment by Saurabh--Kumar** [comment]
@freakboy3742 I have restored @deep110 's implementation of issubset() and is superset() methods. Taking help from his implementation, I have also modified isdisjoint() method to accept iterables.

**Pull request merged**
