### PR TITLE
Implemented splitlines() in Str.java

### PR DESCRIPTION
**Pull request by SouravJohar**
I have added the test cases also, in test_str.java

### CODE REVIEW

**Comment by SouravJohar** [comment]
I've run a lot of test cases on this function, and it works exactly like it has to. The only problem I'm facing is the checkstyle issues. Is there anything else wrong with it? @cflee

**Comment by cflee** [comment]
@SouravJohar 

> I've run a lot of test cases on this function, and it works exactly like it has to. The only problem I'm facing is the checkstyle issues. Is there anything else wrong with it?

I'm not sure which test cases you have run and passed, but I checked out your latest commit (dffce51) locally and your newly added `test_splitlines` fails.

You may want to run `flake8`, `ant checkstyle`, and the relevant tests locally so that you can get immediate feedback instead of waiting for the CI to finish running it.

**Comment by SouravJohar** [comment]
@cflee, I checked again and ran tests locally, and it works. I didn't have to make any changes...
screen shot 2017-03-27 at 2 07 32 pm

**Comment by cflee** [comment]
@SouravJohar 

That's running your own `test.py`, not the test you added to `test_str.py`. I have no idea what is inside your local copy of `test.py`, but here is what I obtain for your test locally:

```
$ python setup.py test -s tests.datatypes.test_str.StrTests.test_splitlines
/Users/cflee/.pyenv/versions/voc/lib/python3.4/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.1.2-dev' to '0.1.2.dev0'
  normalized_version,
running test
running egg_info
writing top-level names to voc.egg-info/top_level.txt
writing voc.egg-info/PKG-INFO
writing entry points to voc.egg-info/entry_points.txt
writing dependency_links to voc.egg-info/dependency_links.txt
reading manifest file 'voc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Makefile'
warning: no files found matching 'requirements*.txt'
writing manifest file 'voc.egg-info/SOURCES.txt'
running build_ext
test_splitlines (tests.datatypes.test_str.StrTests) ... FAIL

======================================================================
FAIL: test_splitlines (tests.datatypes.test_str.StrTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cflee/Projects/voc-dev/voc/tests/utils.py", line 380, in assertCodeExecution
    java_out = self.runAsJava(adj_code, extra_code, args=args)
  File "/Users/cflee/Projects/voc-dev/voc/tests/utils.py", line 544, in runAsJava
    transpiler.transpile_string("test.py", main_code)
  File "<unknown>", line 1
    st="Today
            ^
SyntaxError: EOL while scanning string literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cflee/Projects/voc-dev/voc/tests/datatypes/test_str.py", line 596, in test_splitlines
    """)
  File "/Users/cflee/Projects/voc-dev/voc/tests/utils.py", line 382, in assertCodeExecution
    self.fail(e)
AssertionError: EOL while scanning string literal (<unknown>, line 1)

----------------------------------------------------------------------
Ran 1 test in 4.392s

FAILED (failures=1)
```

You need to run the test suite locally. Please see our [Contributing to VOC](https://voc.readthedocs.io/en/latest/internals/contributing.html#running-the-test-suite) docs page.

**Comment by SouravJohar** [comment]
@cflee, this is what I have in my `test.py`
It is the same as the test case I uploaded in `test_str.py`

st="Today\n\n has been a \n good \n day. \n\n"
try:
        print(st.splitlines(0))
except TypeError as err:
                print(err)
try:
        print(st.splitlines(-1))
except TypeError as err:
        print(err)
try:
        print(st.splitlines())
except TypeError as err:
        print(err)
try:
        print(st.splitlines(10))
except TypeError as err:
        print(err)


...and this was working fine when I ran it on my system. What could be the issue?

**Comment by cflee** [comment]
@SouravJohar Are you able to run the actual test case (not your `test.py`) and replicate the error?

Notice that the whole chunk of python code being passed to `assertCodeExecution()` is actually a very long string. In the string, if you have escape sequences like `\n`, they will be interpreted accordingly. So from this:

```
st="Today\n\n has been"
```

When the test suite is executed, it is being interpreted as this instead:

```
st="Today

 has been"
```

That's why if you look at the test output, python complains of the error
```
    st="Today
            ^
SyntaxError: EOL while scanning string literal
```

To avoid this, you need to escape the backslash, so that it becomes something like:

```
st="Today\\n\\n has been"
```

That way it will be interpreted as the actual two chars of `\n` is in the string, and that's what gets compiled as python code by the test suite.

**Comment by SouravJohar** [comment]
@cflee 
Hey, I've checkstyled my code and also added the escape sequence `\\n` in `test_str.py`
All Travis CI checks have passed, could you review it? Thanks!

**Comment by cflee** [comment]
@SouravJohar Please see the [python docs for str.splitlines()](https://docs.python.org/3.4/library/stdtypes.html#str.splitlines).

The implementation of `splitlines()` needs to handle all the other line boundaries listed in the docs, apart from `\n`. It also needs to handle various other types of keepends parameter, apart from Ints.

(Also, just a note that there is also another open PR (#465) that is also trying to implement `splitlines()`.)

**Comment by cflee** [comment]
Closing as this has been implemented in #566.

**Pull request closed without merging**
