### PR TITLE
Implementing Lambdas

### LINKED ISSUE #347: Missing implementation for lambda syntax
NotImplementedError: No handler for Lambda ,seems lamda functions not working for me, any workaround??

### PR DESCRIPTION
**Pull request by adamrk**
Adding implementation for lambdas. (Closes #347)

### CODE REVIEW

**Comment by eliasdorneles** [comment]
Hey @adamrk !
The build failed because there are [some tests](https://github.com/pybee/voc/blob/master/tests/structures/test_comparisons.py#L497-L543) that were marked as expected failures (w/ the `@expectedFailure`) because of the lack of lambda.
With these changes those tests are now passing. :)
Can you remove the expected failure mark?
Thanks!

**Comment by adamrk** [comment]
Funny! I'll do it tomorrow morning.

On Mar 15, 2017 8:28 PM, "Elias Dorneles" <notifications@github.com> wrote:

Hey @adamrk <https://github.com/adamrk> !
The build failed because there are some tests
<https://github.com/pybee/voc/blob/master/tests/structures/test_comparisons.py#L497-L543>
that were marked as expected failures (w/ the @expectedFailure) because of
the lack of lambda.
With these changes those tests are now passing. :)
Can you remove the expected failure mark?
Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pybee/voc/pull/427#issuecomment-286921809>, or mute the
thread

**Comment by adamrk** [comment]
@freakboy3742 : moved some of the common code into the method `_create_function`.

**Comment by eliasdorneles** [comment]
I'd love some other maintainer to give a final review to this one, since I've been pairing with @adamrk on this and it looks good to me. =)

**Comment by eliasdorneles** [comment]
Thanks for contributing @adamrk, nice pairing with you! :+1:

**Comment by adamrk** [comment]
Thanks @eliasdorneles !

**Pull request merged**
