### PR TITLE
Small Python 3 checking fixes.

### PR DESCRIPTION
**Pull request by mithro**

### CODE REVIEW

**Comment by freakboy3742** [comment]
I like the idea; but if you put logic in the setup.py, you can't create a wheel. A better place for that logic would be in the mainline for starting the voc command line tool.

**Comment by mithro** [comment]
Why does the check in setup.py prevent creating a wheel?

**Comment by freakboy3742** [comment]
AFAIK, you can't have install-modifying logic in a setup.py. The setup.py isn't executed as part of a wheel install, so if there is anything install-location-dependent in your setup.py, it won't be run.

**Comment by mithro** [comment]
This check just prevents you from (hopefully accidentally) running setup.py with Python 2?

When creating wheels they will already be tagged as Python 3 specific if I understand correctly?

**Comment by mithro** [comment]
@freakboy3742 Friendly ping?

**Comment by freakboy3742** [comment]
@mithro Apologies for the delay in addressing this - it fell of my radar.

**Comment by mithro** [comment]
It fell off my radar too which is why I only pinged then :).

**Pull request merged**
