### PR TITLE
Bytes type

### PR DESCRIPTION
**Pull request by thefon**
Signed-off-by: Adrian Smith <fon@thefon.net>

### CODE REVIEW

**Comment by thefon** [comment]
Failing only due to travis timeout.

**Comment by freakboy3742** [comment]
Almost there - there's just the 52 unexpected successes to deal with. Delete them from the various `not_implemented` lists where they appear, and this will be good to merge!

**Comment by thefon** [comment]
Ahh yes, I was looking for that.  I think many of them are in other tests
from what I am working on (Bytes) that I have indirectly made work.

Also had to hardcode all the differences between Python 3.5 (my system),
and Python 3.4 (Travis).   :(

**Comment by thefon** [comment]
Yay!

**Pull request merged**
