### PR TITLE
added replace() function

### PR DESCRIPTION
**Pull request by AakashSasikumar**
added my implementation of the replace() function along with the test_str.py

### CODE REVIEW

**Comment by AakashSasikumar** [comment]
Sure, I'll get working on that asap.

**Comment by AakashSasikumar** [comment]
I have updated my code for a bug that I found. Also, I've added more test cases like you asked.

**Comment by cflee** [comment]
@AakashSasikumar As there is a merge conflict, could you rebase this on/merge in latest master branch please? I'm not too sure what's going on but there seem to be changes for rstrip/lstrip/strip included in the last few commits, which is a little unexpected.

**Comment by AakashSasikumar** [comment]
sure thing

**Comment by AakashSasikumar** [comment]
Why is the merge conflict still there? I've changed the test_str.py.

**Comment by goanpeca** [comment]
@AakashSasikumar could you rebase/merge with the latest master and update this PR. After that are there still missing tests?

**Comment by cflee** [comment]
Closing, as this was implemented in #501.

**Pull request closed without merging**
