### PR TITLE
Updating getting started docs for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by wesseljb**
Added the change to the apt-get command to work with the apt-get command on ubuntu 16.04

### CODE REVIEW

**Comment by freakboy3742** [comment]
To clarify - I'm not suggesting that you need to provide all the details for the other operating systems - just set up the broad structure so that someone else could add them easily if they wanted to.

**Comment by wesseljb** [comment]
sure, I will do that


On 21 September 2016 at 10:22, Russell Keith-Magee <notifications@github.com

**Comment by wesseljb** [comment]
I have pushed up changes to try and make provision for other operating systems.

**Comment by freakboy3742** [comment]
Fantastic! Thanks for the contribution!

**Comment by wesseljb** [comment]
Thanks, hopefully I can contribute to the code soon.

On 21 September 2016 at 10:32, Russell Keith-Magee <notifications@github.com

**Pull request merged**
