### PR TITLE
__mul__ function now working for the Str type and Int type

### PR DESCRIPTION
**Pull request by dibyadas**
I have fixed a minor issue in the implementation of the  \_\_mul\_\_ for Int and Str types. 
``` 
print("test".__mul__(3)) 
```
or
```
a = 3 
print(a.__mul__(3))
``` 
used to give an error:-
```
Exception in thread "main" TypeError: __mul__() takes 0 positional arguments but 1 was given
	at org.python.types.Function.throwUnexpectedPositionalArgumentsError(Function.java:220)
	at org.python.types.Function.adjustArguments(Function.java:260)
	at org.python.types.Function.invoke(Function.java:373)
	at org.python.types.Method.invoke(Method.java:48)
	at python.bool.__init__.module$import(bool.py:1)
	at python.bool.__init__.main(bool.py
```
while the expected output was supposed to be :-
```
"testtesttest"
```
and
```
9
```

I edited the \_\_mul\_\_ function annotations in org/python/types/Int.java and Str.java  to fix it.

Please suggest improvements, if any! :smile:

### CODE REVIEW

**Comment by cflee** [comment]
This does look like it works, but we need to have tests to ensure that it keeps working in the future... and unfortunately that opens a can of worms, as it becomes related to #212 and #213.

**Comment by dibyadas** [comment]
@cflee @freakboy3742 Thanks for reviewing my PR!  I will try to resolve the issues as soon as possible.

**Comment by goanpeca** [comment]
@dibyadas could you rebase this PR with the latest master to enable the latest CI checks.

Have you had some time to add some extra tests to this? Need some help?

Cheers :-)

**Comment by dibyadas** [comment]
@goanpeca I have replied to your comment [here](https://github.com/pybee/voc/pull/470#issuecomment-321825565).  :slightly_smiling_face:

**Comment by cflee** [comment]
Closing, as this fix was implemented in #644.

**Pull request closed without merging**
