### PR TITLE
This fixes all tests for NoneType datatype.

### PR DESCRIPTION
**Pull request by student-06**
#36

### CODE REVIEW

**Comment by eliasdorneles** [comment]
This PR contains change from the PR about slices as well.
In these cases, your options are:
1) wait until the other PR gets merged, and then rebase this one
2) send the changes in the same PR

Normally it's best to always start each PR on a new branch on top of master, even if there is some common code between them: and then merge them later as needed.

For this case, you can probably just wait because I believe the other PR w/ common code with this one will get merged soon. :)

**Comment by student-06** [comment]
@eliasdorneles

**Comment by eliasdorneles** [comment]
@student-06 You don't need to close the PR, if you [synchronize your local master](https://help.github.com/articles/syncing-a-fork/), then [rebase the branch on top of it](https://help.github.com/articles/about-git-rebase/) and then force push, the PR will be updated.

**Comment by student-06** [comment]
@eliasdorneles sorry for the trouble and thanks for the suggestion to fix it. I am trying it out.

**Comment by eliasdorneles** [comment]
No worries, no need to be sorry -- it's all learning!
Btw, I know that rebasing can be a scary concept if you haven't done it before, take your time and [don't be scared of it](https://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/). =)

**Comment by student-06** [comment]
Hi @eliasdorneles. I did rebase and now my working branch and master both are having the same commit on their top. Now where should I push to ```master``` or ```fix_nonetype``` branch.

**Comment by eliasdorneles** [comment]
Hm, did you manage to [synchronize your repo](https://help.github.com/articles/syncing-a-fork/) before doing the rebase?

**Comment by student-06** [comment]
Yes I did merge.

**Comment by eliasdorneles** [comment]
@student-06 To verify it's correct, you can look at the diff shown for your PR -- after the correct synchronization the diff would not show the addition of the `isSequence` method (because it's already added in the `master` branch).

**Comment by student-06** [comment]
@eliasdorneles Hi, I actually messed up the my master while doing rebase and also polluted my current branch. So I did reset my master with upstream/master. And then did reflog on current branch to get HEAD of the branch to this the unmerged [commit](https://github.com/pybee/voc/pull/745/commits/1378866ec44aac9c62d53b911a0ce774497a256e). Then I did made this [new branch](https://github.com/student-06/voc/tree/fix_nonetype1), and did ```git pull --rebase``` and now I have a proper order of commit i.e my unmerged commit on top and below it commits from upstream/master. Is it fine if I create new pull request for the this one from [this branch](https://github.com/student-06/voc/tree/fix_nonetype1) since the old branch is messed up ?
I kind of messed up this but learnt some lessons.
Thank you.

**Comment by eliasdorneles** [comment]
@student-06 oh yeah, feel free to send another PR -- keeping this one was just a suggestion. :)

**Comment by student-06** [comment]
@eliasdorneles Thanks for the help. I made another pull request #749

**Pull request closed without merging**
